<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class AlatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kategori = DB::table('kategoris')->get()->keyBy('nama_kategori');

         DB::table('alats')->insert([
            // Kantor Bmkg
            [
                'nama_alat' => 'Sangkar Meteorologi',
                'merek_tipe' => 'Kayu Lokal',
                'jumlah' => 1,
                'tahun_pemasangan' => 2004,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer BB/BK',
                'merek_tipe' => 'Scheneider',
                'jumlah' => 2,
                'tahun_pemasangan' => 2000,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer BB/BK',
                'merek_tipe' => 'F.Ketterer',
                'jumlah' => 2,
                'tahun_pemasangan' => 2011,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Max./Min',
                'merek_tipe' => 'Scheneider',
                'jumlah' => 1,
                'tahun_pemasangan' => 1968,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Max./Min',
                'merek_tipe' => 'Scheneider',
                'jumlah' => 1,
                'tahun_pemasangan' => 1994,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Max./Min',
                'merek_tipe' => 'Scheneider',
                'jumlah' => 1,
                'tahun_pemasangan' => 2000,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Max./Min',
                'merek_tipe' => 'F.Ketterer',
                'jumlah' => 1,
                'tahun_pemasangan' => 2011,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barograph',
                'merek_tipe' => 'J.Richard',
                'jumlah' => 1,
                'tahun_pemasangan' => 1976,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barometer Digital',
                'merek_tipe' => 'Vaisalla PTB 330',
                'jumlah' => 1,
                'tahun_pemasangan' => 2012,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Anemometer Digital',
                'merek_tipe' => 'RM.Young',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Cup Counter Anemometer',
                'merek_tipe' => 'DR.A.Muller/91 g',
                'jumlah' => 1,
                'tahun_pemasangan' => 2003,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Panci Penguapan',
                'merek_tipe' => 'Lokal',
                'jumlah' => 1,
                'tahun_pemasangan' => 1978,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Steel Well & Hook Gauge',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 1978,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Apung',
                'merek_tipe' => 'Clima',
                'jumlah' => 1,
                'tahun_pemasangan' => 2013,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Campbell Stokes',
                'merek_tipe' => 'Casella - 9900',
                'jumlah' => 1,
                'tahun_pemasangan' => 1977,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Penakar Hujan Obs',
                'merek_tipe' => 'Type Obs-Standars',
                'jumlah' => 1,
                'tahun_pemasangan' => 2010,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Penakar Hujan Helmann',
                'merek_tipe' => 'LokaHelmann 9096/Casellal',
                'jumlah' => 1,
                'tahun_pemasangan' => 2010,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => ' Theodolite',
                'merek_tipe' => 'W. Knight No.284420',
                'jumlah' => 1,
                'tahun_pemasangan' => 2010,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //AWS Digital
            [
                'nama_alat' => 'Temperature & Humidity Sensor',
                'merek_tipe' => 'Vaisala/HMP155',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barometer Sensor',
                'merek_tipe' => 'Vaisala/PTB330',
                'jumlah' => 2,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Water Thermometer',
                'merek_tipe' => 'Vaisala/QMT110',
                'jumlah' => 2,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Wind Speed Evaporation',
                'merek_tipe' => 'Vaisala/WAA151',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Ultrasonic Sensor',
                'merek_tipe' => 'Vaisala/WMT703',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Tipping Bucket',
                'merek_tipe' => 'Vaisala/RG13N2NN',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Water Level',
                'merek_tipe' => 'Thies Clima/6143210073',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Lightning Detector',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Data Logger',
                'merek_tipe' => 'Campbel Scientific/CR3000',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'PC Server',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'PC Client',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'UPS',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Radio Link- Tm. Alat(192.168.2.30)',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Radio Link- PC(192.168.2.20)',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'HUB',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => ' Monitor',
                'merek_tipe' => 'Samsung',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWS Digital']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //Pos Meteorologi Bandara Banyuwangi
            [
                'nama_alat' => 'Sangkar Meteorologi',
                'merek_tipe' => 'Kayu Lokal',
                'jumlah' => 1,
                'tahun_pemasangan' => 2012,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer BB/BK',
                'merek_tipe' => 'F. Ketterer',
                'jumlah' => 2,
                'tahun_pemasangan' => 2011,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Max./ Min',
                'merek_tipe' => 'F. Ketterer',
                'jumlah' => 1,
                'tahun_pemasangan' => 2011,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Max./Min',
                'merek_tipe' => 'Scheneider',
                'jumlah' => 1,
                'tahun_pemasangan' => 2000,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barograph',
                'merek_tipe' => 'DR.A.Muller/R.Fuess',
                'jumlah' => 1,
                'tahun_pemasangan' => 2012,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Max./Min',
                'merek_tipe' => 'Scheneider',
                'jumlah' => 1,
                'tahun_pemasangan' => 2000,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Thermometer Max./Min',
                'merek_tipe' => 'F.Ketterer',
                'jumlah' => 1,
                'tahun_pemasangan' => 2011,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barograph',
                'merek_tipe' => 'J.Richard',
                'jumlah' => 1,
                'tahun_pemasangan' => 2012,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barometer Digital',
                'merek_tipe' => 'Vaisalla PTB 330',
                'jumlah' => 1,
                'tahun_pemasangan' => 2013,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Anemometer Digital',
                'merek_tipe' => 'RM.Young',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Penakar Hujan Obs',
                'merek_tipe' => 'Type Obs-Standars',
                'jumlah' => 1,
                'tahun_pemasangan' => 2003,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Display Cuaca Bandara Banyuwangi',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2015,
                'kategori_id' => $kategori['Peralatan Konvensional']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Pos Meteorologi Bandara Banyuwang (AWOS Kategori 3 All Weather)
            //RW 08
            [
                'nama_alat' => 'Temperature & Humidity Sensor',
                'merek_tipe' => 'Model 5190-F',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Mars',
                'merek_tipe' => 'Model 8190',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barometer Sensor',
                'merek_tipe' => 'Model 7150 Series',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Ultrasonic Wind Sensor',
                'merek_tipe' => 'Model 2040',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Optical Rain Gauge',
                'merek_tipe' => 'Model 6030',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'DCP',
                'merek_tipe' => 'Model 1191-I',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'UPCM',
                'merek_tipe' => 'Module- BCS24',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Visibility Sensor',
                'merek_tipe' => '8364 series',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Ceilometer laser',
                'merek_tipe' => 'Model 8339',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Ceilometer Blower',
                'merek_tipe' => 'Bcs24',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Ceilometer DAC Board',
                'merek_tipe' => 'Bcs24',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Pyranometer',
                'merek_tipe' => 'Model 3016',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'MOXA',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Wirreles',
                'merek_tipe' => 'TP Link',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //MIDDLE
            [
                'nama_alat' => 'Temperature & Humidity Sensor',
                'merek_tipe' => 'Model 5190-F',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Mars',
                'merek_tipe' => 'Model 8190',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Barometer Sensor',
                'merek_tipe' => 'Model 7150 Series',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Tipping Bucket',
                'merek_tipe' => 'Model 6011',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'DCP',
                'merek_tipe' => 'Model 1191-I',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Antenna lightning sensor',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Processor Lightning',
                'merek_tipe' => 'Model 6500',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'SS Radio',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Pyranometer',
                'merek_tipe' => 'Model 3016',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'MOXA',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //RWY 26
            [
                'nama_alat' => 'Temperature & Humidity Sensor',
                'merek_tipe' => 'Model 5190-F',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Mars',
                'merek_tipe' => 'Model 8190',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Barometer Sensor',
                'merek_tipe' => 'Model 7150 Series',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Ultrasonic Wind Sensor',
                'merek_tipe' => 'Model 2040',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Optical Rain Gauge',
                'merek_tipe' => 'Model 6030',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'DCP',
                'merek_tipe' => 'Model 1191-I',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'UPCM',
                'merek_tipe' => 'Module- BCS24',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Visibility Sensor',
                'merek_tipe' => '8364 series',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Ceilometer laser',
                'merek_tipe' => 'Model 8339',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Ceilometer Blower',
                'merek_tipe' => 'Bcs24',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Ceilometer DAC Board',
                'merek_tipe' => 'Bcs24',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Pyranometer',
                'merek_tipe' => 'Model 3016',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'MOXA',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'SS Radio',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Solar Panel',
                'merek_tipe' => '-',
                'jumlah' => 10,
                'tahun_pemasangan' => 2024,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Baterai (aki)',
                'merek_tipe' => '-',
                'jumlah' => 10,
                'tahun_pemasangan' => 2024,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'MPPT',
                'merek_tipe' => '-',
                'jumlah' => 2,
                'tahun_pemasangan' => 2024,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Inverter',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2024,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Stabilizer',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2024,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //SERVER 
            [
                'nama_alat' => 'CDP 1',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'CDP 2',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'SS Radio',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Wirreles',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'UPS Server',
                'merek_tipe' => 'APC',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'Monitor',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'PC Client',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'UPS Client',
                'merek_tipe' => 'APC',
                'jumlah' => 1,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //PC Awos Client ATC
            [
                'nama_alat' => 'PC Client',
                'merek_tipe' => '-',
                'jumlah' => 2,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'UPS',
                'merek_tipe' => 'APC',
                'jumlah' => 2,
                'tahun_pemasangan' => 2018,
                'kategori_id' => $kategori['AWOS Kategori 3 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Pos Meteorologi Bandara Banyuwangi (Peralatan pendukung)
            [
                'nama_alat' => 'PC Forecast',
                'merek_tipe' => 'Asus',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'PC Obs',
                'merek_tipe' => 'Asus',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'UPS PC Forecast',
                'merek_tipe' => 'Samuto',
                'jumlah' => 1,
                'tahun_pemasangan' => 2025,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'UPS PC Obs',
                'merek_tipe' => 'APC',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Printer',
                'merek_tipe' => 'Epson',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Modem',
                'merek_tipe' => 'Alcatel Lucent',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Hub',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Pos Meteorologi Pelabuhan Ketapang Banyuwangi (AWS Maritim)
            [
                'nama_alat' => 'Logger',
                'merek_tipe' => 'Vaisala',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Anemometer',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Suhu dan Kelembaban',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Pyranometer',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Typing bucket',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barometer',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Water Temp',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Water Level',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => ' Radar Maritim',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Baterai',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Solar Cell',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Solar Charger',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => ' Visibility',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => 2025,
                'kategori_id' => $kategori['AWS Maritim']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Pos Meteorologi Pelabuhan Ketapang Banyuwangi (Peralatan Pendukung)
            [
                'nama_alat' => 'PC Obs',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Printer',
                'merek_tipe' => 'Epson',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Modem',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'UPS',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Display Maritim Ketapang',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Pos Meteorologi Bandara Notohadinegoro Jember(AWOS Kategori 1 All)
            [
                'nama_alat' => 'Temperature & Humidity Sensor',
                'merek_tipe' => 'Model 5190-F',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Sars',
                'merek_tipe' => 'Model 8141',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Barometer Sensor',
                'merek_tipe' => 'Model 7150 Series',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Ultrasonic Wind Sensor',
                'merek_tipe' => 'Model 9620',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Tipping Bucket',
                'merek_tipe' => 'Model 6011',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'DCP',
                'merek_tipe' => 'Model 1191-I',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Pyranometer',
                'merek_tipe' => 'Model 3016',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'MOXA',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Wirreles',
                'merek_tipe' => 'TP Link',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'CDP Server',
                'merek_tipe' => 'Dell',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'CDP Client',
                'merek_tipe' => 'Dell',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'UPS',
                'merek_tipe' => 'APC',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['AWOS Kategori 1 All Weather']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Pos Meteorologi Bandara Notohadinegoro Jember (RAMI)
            [
                'nama_alat' => 'Monitor RAMI',
                'merek_tipe' => 'Samsung',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['RAMI']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'CPU RAMI',
                'merek_tipe' => 'HP',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['RAMI']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'UPC',
                'merek_tipe' => 'APC',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['RAMI']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'nama_alat' => 'CCTV',
                'merek_tipe' => 'AIK Vision',
                'jumlah' => 2,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['RAMI']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Pos Meteorologi Bandara Notohadinegoro Jember (Peralatan Pendukung)
            [
                'nama_alat' => 'PC Obs',
                'merek_tipe' => 'DELL',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Printer',
                'merek_tipe' => 'Epson L360',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Modem',
                'merek_tipe' => 'ZTE',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_alat' => 'Display Cuaca Bandara Noto Hadinegoro',
                'merek_tipe' => '-',
                'jumlah' => 1,
                'tahun_pemasangan' => null,
                'kategori_id' => $kategori['Peralatan Pendukung']->id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
